# Generated by Django 3.0.6 on 2020-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='vetements',
            field=models.ManyToManyField(to='shopping.Vetement'),
        ),
    ]
