# Generated by Django 3.0.6 on 2020-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200525_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vetements',
            new_name='Vetement',
        ),
        migrations.AlterModelOptions(
            name='vetement',
            options={'verbose_name': 'Vetement', 'verbose_name_plural': 'Vetements'},
        ),
    ]
