# Generated by Django 3.0.6 on 2020-05-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200525_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vetement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.Vetement'),
        ),
    ]
