# Generated by Django 3.0.6 on 2020-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200525_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetement',
            name='image',
            field=models.ImageField(default='/media/robe.jpg', null=True, upload_to=''),
        ),
    ]
