# Generated by Django 3.0.6 on 2020-05-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shopping', '0007_auto_20200526_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('vetement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping.Vetement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shopping.vetement',),
        ),
        migrations.CreateModel(
            name='Robe',
            fields=[
                ('vetement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping.Vetement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shopping.vetement',),
        ),
        migrations.AddField(
            model_name='vetement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_shopping.vetement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
