# Generated by Django 3.0.6 on 2020-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200526_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetement',
            name='image',
            field=models.ImageField(default='/robe.jpg', null=True, upload_to=''),
        ),
    ]
