# Generated by Django 3.0.6 on 2020-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20200526_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetement',
            name='image',
        ),
        migrations.AddField(
            model_name='pantalon',
            name='image',
            field=models.ImageField(default='/pantalon.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='robe',
            name='image',
            field=models.ImageField(default='/robe.jpg', null=True, upload_to=''),
        ),
    ]
