# Generated by Django 3.0.6 on 2020-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20200526_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='image',
            field=models.ImageField(blank=True, default='/pantalon.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='robe',
            name='image',
            field=models.ImageField(blank=True, default='/robe.jpg', upload_to=''),
        ),
    ]
