# Generated by Django 3.0.6 on 2020-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20200526_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='color',
            field=models.CharField(choices=[('blue', 'Bleu'), ('red', 'Rouge'), ('green', 'Vert'), ('yellow', 'Jaune'), ('purple', 'Violet')], default='blue', max_length=15),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='description',
            field=models.TextField(help_text='Une courte description'),
        ),
    ]
